quarkus.smallrye-openapi.enabled=true
quarkus.smallrye-openapi.path=/openapi
quarkus.smallrye-openapi.title=Games, games, games
quarkus.smallrye-openapi.description=API documentation for Games
quarkus.smallrye-openapi.version=1.0.0
